name: broadcast_wsrpc
description: An wsrpc client implementation
version: 0.1.0
homepage: https://github.com/raffber/wsrpc

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  uuid: ^3.0.6
  async: ^2.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  path: ^1.8.2
