name: CI

on:
  push:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore cargo cache
      uses: actions/cache@v2
      env:
        cache-name: ci
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          rust/target
        key: ubuntu-${{ env.cache-name }}-${{ hashFiles('rust/Cargo.lock') }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
        components: clippy, rustfmt
    
    - name: Build Debug
      run: cd rust && cargo build

    - name: Run tests
      run: cd rust && cargo test

    - name: Run clippy
      run: cd rust && cargo clippy

    - name: Check formatting
      run: cd rust && cargo fmt -- --check
